### PR TITLE
improve tests for public interface

### PR DESCRIPTION
**Pull request by moshensky**
@mzl-md I have added a test that asserts new options. While writing it I have noticed that highlight color was not picked up at all. In my particular case the issue is quotation of the option inside gm lib https://github.com/aheckmann/gm/blob/e715cbdaacad21504fc04f6933be5cae1812501e/lib/compare.js#L37. 
Can you confirm if it works for you out of the box?

### CODE REVIEW

**Comment by mzl-md** [comment]
No it doesn't seem to work for me either. Maybe I changed it in the gm lib when trying why it wasn't working. I can confirm it works without the lines in gm with `yellow' and 'Yellow':
```ts
if (options.highlightColor && options.highlightColor.indexOf('"') < 0) {
    options.highlightColor = '"' + options.highlightColor + '"';
}
```

Version 0.2.0 seems to not contain the code changes from my PR, did you build before releasing the package?

**Comment by moshensky** [comment]
> Version 0.2.0 seems to not contain the code changes from my PR, did you build before releasing the package?

Feel stupid. This needs some automation. I will fix it asap.

**Comment by mzl-md** [comment]
There's an issue in the gm lib for this (https://github.com/aheckmann/gm/issues/480), but with >300 open issues, copying the code seems reasonable.

**Comment by moshensky** [comment]
> There's an issue in the gm lib for this ([aheckmann/gm#480](https://github.com/aheckmann/gm/issues/480)), but with >300 open issues, copying the code seems reasonable.

exactly what I thought

**Pull request merged**
