### PR TITLE
Allow configuration of compare-images

### PR DESCRIPTION
**Pull request by mzl-md**
Changes:
- typo `yellow` in compare-images, must be `Yellow`
- enable configuration of compareImages in comparePdfToSnapshot
- if tests fail in github actions: store snapshots as build artifacts so they can be reviewed later

### CODE REVIEW

**Comment by mzl-md** [comment]
Hi @moshensky , do you know when you get to review (and hopefully release) this?  I would really appreciate to use the module but without the tolerance flag the tests always fail on some images inside the pdf.

**Comment by moshensky** [comment]
Hi @mzl-md sorry for the late reply. I will have a look asap. Latest tomorrow morning.

**Review by moshensky — APPROVED** [review]
👍 
As a small improvement might be adding a test that makes sure that public interface is exercised, i.e. adding one test with options that would overwrite defaults.

**Comment by moshensky** [comment]
> Hi @moshensky , do you know when you get to review (and hopefully release) this? I would really appreciate to use the module but without the tolerance flag the tests always fail on some images inside the pdf.

@mzl-md I released it: https://www.npmjs.com/package/pdf-visual-diff

**Comment by mzl-md** [comment]
Great, thank you!

> As a small improvement might be adding a test that makes sure that public interface is exercised, i.e. adding one test with options that would overwrite defaults.

I thought about that but was not sure how to check that the overwritten defaults are being applied.
Also the README could be updated with the new params. Maybe I'll get to that later.

**Pull request merged**
